const CONTRACT_ADDRESS_FREAK = process.env.REACT_APP_CONTRACT_ADDRESS_FREAK;
const CONTRACT_ADDRESS_USDC = process.env.REACT_APP_CONTRACT_ADDRESS_USDC;
const CONTRACT_ADDRESS_PROFIT = process.env.REACT_APP_CONTRACT_ADDRESS_PROFIT;

export default {
  CONTRACT_ADDRESS_FREAK,
  CONTRACT_ADDRESS_USDC,
  CONTRACT_ADDRESS_PROFIT,
};
